export const config = {
  github: {
    token: process.env.GH_TOKEN,
    organization: "instea",
    // instea-dev
    teamId: 2469941,
  },
  // all repos to be migrated
  repoNames: [
    "legal-templates",
    "aws-rds-test",
    "minutovy-grafik",
    "rabona",
    "openapi-hackathlon-2021",
    "GS-Finances-Predictions",
    "Internal-Google-Scripts",
    "expo-monorepo",
    "vifzack",
    "internet-checker",
    "tmp-my-codi",
    "scraping",
    "app-script-sheets-wrapper",
    "instea-processes",
    "kubernetes-demos",
    "app-script-demo-lib",
    "slab-import",
    "internal-app-scripts",
    "html-to-pdf",
    "machine-monitoring",
    "eaukcie",
    "instea-templates",
    "wiki",
    "coding-stats",
    "finances",
    "sample-lerna",
    "quick-poc-gps",
    "mhd-prediction",
    "attendance-gs",
    "mapar",
    "map-recognition",
    "sp-500-parser",
    "sso-metadata",
    "toggl-calendar",
    "labeler",
    "ny-most-popular",
    "spring-data-example",
    "toggl-tempo",
    "docker-test",
    "temp-mo",
    "conference-pwa-tools",
    "festival-svetla",
    "conference-pwa",
    "kickass-lib",
    "woef",
    "qms-clone",
    "codecon",
    "sport-events",
    "paintiano",
    "insteaWeb",
    "secret-keys",
    "qadash",
    "instea-knowledgebase",
    "techtalks-samples",
  ],
  // "git url prefix",
  srcGitPrefix: "git@gitlab.com:instea.sk/",
};
